### ISSUE TITLE
个人主页UI的BUG

### ISSUE THREAD

**Issue by zeroRains** [zeroRains/SharePhoto#7]
点进个人主页后，在点进其他的地方，会产生奇怪的白条
![DHNI~O 21EC 5_(M_%B97U5](https://user-images.githubusercontent.com/57100978/130620780-5e422a3d-4c2f-4747-a92a-11179d07d91f.jpg)

还有就是，在个人主页后向上滑动，会进入白色的地方，然后就拉不回来了
![image](https://user-images.githubusercontent.com/57100978/130620948-326b881f-ad38-452c-b0fe-2c2e554d3dc5.png)

assiment to @PommesPeter

**Comment by PommesPeter** [comment]
> 点进个人主页后，在点进其他的地方，会产生奇怪的白条
> ![DHNI~O 21EC 5_(M_%B97U5](https://user-images.githubusercontent.com/57100978/130620780-5e422a3d-4c2f-4747-a92a-11179d07d91f.jpg)
> 
> 还有就是，在个人主页后向上滑动，会进入白色的地方，然后就拉不回来了
> ![image](https://user-images.githubusercontent.com/57100978/130620948-326b881f-ad38-452c-b0fe-2c2e554d3dc5.png)
> 
> assiment to @PommesPeter

合并之后还没测呢。。

**Comment by PommesPeter** [comment]
刚才一弄可能乱了

**Comment by PommesPeter** [comment]
拉动的那个问题应该是设错滑动的那个layout的，应该是通过recyclerview来实现上方的滑动，现在相当于是滑动整个界面了

**Comment by zeroRains** [comment]
> 拉动的那个问题应该是设错滑动的那个layout的，应该是通过recyclerview来实现上方的滑动，现在相当于是滑动整个界面了

快通宵，晚上起来上厕所的时候看看你

**Comment by PommesPeter** [comment]
> > 拉动的那个问题应该是设错滑动的那个layout的，应该是通过recyclerview来实现上方的滑动，现在相当于是滑动整个界面了
> 
> 快通宵，晚上起来上厕所的时候看看你

找到原因了，是滑动那个layout的问题，我先写好那三个fragment再加滑动

**Comment by PommesPeter** [comment]
> > > 拉动的那个问题应该是设错滑动的那个layout的，应该是通过recyclerview来实现上方的滑动，现在相当于是滑动整个界面了
> > 
> > 
> > 快通宵，晚上起来上厕所的时候看看你
> 
> 找到原因了，是滑动那个layout的问题，我先写好那三个fragment再加滑动

啊这。。并没有解决。。

**Comment by PommesPeter** [comment]
> > > > 拉动的那个问题应该是设错滑动的那个layout的，应该是通过recyclerview来实现上方的滑动，现在相当于是滑动整个界面了
> > > 
> > > 
> > > 快通宵，晚上起来上厕所的时候看看你
> > 
> > 
> > 找到原因了，是滑动那个layout的问题，我先写好那三个fragment再加滑动
> 
> 啊这。。并没有解决。。

解决了，coordinatorLayout的问题
